Update dependencies
mapbox/dyno pull request #154
Opened 2021-09-20 18:08 UTC by mapsam

Updates all critical severity dependencies (or parents thereof) according to dependabot https://github.com/mapbox/dyno/security/dependabot?q=is%3Aopen+sort%3Aseverity

2021-09-20 19:52 UTC, michaelskahn requested changes
The code changes look fine, but there are a few dependency chain issues to fully support Node 12+.

2021-09-20 19:52 UTC, michaelskahn commented on CHANGELOG.md
> +## v1.5.0
Should this be a major version bump, considering the drop in support for old Node versions?

2021-09-20 19:52 UTC, michaelskahn commented on package.json
>      "@mapbox/dynamodb-test": "^0.3.0",
The dependency on `@mapbox/dynamodb-test` causes some issues with Node 12 on MacOS, because it [depends](https://github.com/mapbox/dynamodb-test/blob/master/package.json#L30) on an old version of `dynalite` that depends on a version of `leveldown` that doesn't have prebuilt binaries for Node 12 (`leveldown@5` is the [minimum required version](https://github.com/Level/leveldown#supported-platforms)). `@mapbox/dynamodb-test` needs to get its version of `dynalite` bumped to the next major version.

2021-09-20 21:53 UTC, mapsam commented on package.json
>      "@mapbox/dynamodb-test": "^0.3.0",
Ah thanks for the confirmation @michaelskahn - I'll get a dynamodb-test update going

2021-09-20 21:53 UTC, mapsam commented on CHANGELOG.md
> +## v1.5.0
I can go either way - the last node.js version drop was not even a release, and subsequent releases were just patches

2021-09-20 22:02 UTC, mapsam commented on package.json
>      "@mapbox/dynamodb-test": "^0.3.0",
https://github.com/mapbox/dynamodb-test/pull/5

2021-09-20 22:09 UTC, michaelskahn commented on package.json
> +    "dynalite": "^3.2.1",
Also, is this new dependency supposed to be here?

2021-09-20 22:11 UTC, mapsam commented on package.json
> +    "dynalite": "^3.2.1",
nope! accidentally installed this when updating dynalite (didn't realize it was in dynamodb-test originally). I'll remove 👍

2021-09-20 22:24 UTC, mapsam commented on package.json
> +    "dynalite": "^3.2.1",
removed in https://github.com/mapbox/dyno/pull/154/commits/154f2d21e16b56fd9dc65e8e5b6500d2d037d037

2021-09-21 14:28 UTC, michaelskahn approved these changes

2021-09-21 16:11 UTC, merged