Support pass costLogger
mapbox/dyno pull request #158
Opened 2023-02-01 13:58 UTC by miafan23

2023-02-01 21:05 UTC, AlexanderBelokon requested changes
This is great, minimal changes to the interface and a cool feature)

I left some comments about edge cases that might come up, and a problem I noticed. Please take a look

2023-02-02 14:12 UTC, miafan23 commented on lib/util.js
> +    listTables: requestHandler(costLogger, client.listTables.bind(client), getMethodType('listTables')),
Thanks for catching this! All table-related methods do not support `ReturnConsumedCapacity` params. And we only use dynomoDBClient for table related methods, so I removed `wrapClient` function

2023-02-09 14:01 UTC, AlexanderBelokon commented on lib/util.js
> +    let start = Date.now();
I'd prefer to declare `start` as `const` as close as possible to its usage, rather than reassign it. This will also avoid problems if the the callback is called multiple times before the first call returns

2023-02-09 14:06 UTC, AlexanderBelokon commented on lib/util.js
> +      start = Date.now();
This could lead to unexpected results if `start` is defined outside of this function

2023-02-14 19:11 UTC, AlexanderBelokon reviewed
This looks good, but I'd hold off on a production release until we get a project to adopt this to iron out as much unknowns as possible.

2023-02-28 11:44 UTC, miafan23 commented on package.json
> +  "version": "1.6.0-alpha",
I'll set it as `1.6.0` before merge

2023-03-02 23:22 UTC, davidweimapbox approved these changes
LGTM

2023-03-03 01:03 UTC, AlexanderBelokon approved these changes

2023-03-10 11:29 UTC, Miroko commented on index.js
> +function Dyno(options, dynoInstance) {
Looks like passing `dynoInstance` won't work with `Dyno.multi`. Is this by design or should this also work with multi?

2023-03-10 15:18 UTC, AlexanderBelokon commented on index.js
> +function Dyno(options, dynoInstance) {
Great find, thanks!

2023-03-14 09:37 UTC, miafan23 commented on index.js
> +    if (Object.keys(options).some(o => ['region', 'endpoint', 'table'].includes(o))) {
@AlexanderBelokon I made some changes there to allow for options other than `costLogger`, as there might be other options like `read` and `write`. I only rejected options containing basic table config remind the user that there's no need to provide DynamoDB config.

2023-03-14 09:41 UTC, miafan23 commented
@Miroko Thank you so much for catching this. We did miss this method! I did some updates to make the dynamoInstance to be as part of the options so that it is easy to reuse the client for `multi` method.
The usage could be seen in this [unit test](https://github.com/mapbox/dyno/pull/158/files#diff-af95cb6f5f65fe70216ddce70325e785438d5aaff956a0666ebf46ef6402f526R197
)

2023-03-14 11:32 UTC, Miroko approved these changes
Thanks for adding the support for `multi`! Looks nice 👍

2023-03-14 14:23 UTC, AlexanderBelokon approved these changes
Awesome work! Can't wait to use it 🔥

2023-03-14 15:08 UTC, merged